[package]
name = "poz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "=1.0.71"
dotenvy = "=0.15.7"
tokio = { version = "=1.29.1", features = ["full"] }
tracing = "=0.1.37"
tracing-subscriber = "=0.3.17"
twilight-cache-inmemory = "=0.15.2"
twilight-gateway = "=0.15.2"
twilight-http = "=0.15.2"
twilight-model = "=0.15.2"

[features]
default = ["twilight-gateway/rustls-webpki-roots", "twilight-http/rustls-webpki-roots"]
